// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOAAh9BLwoId8YhH-mxF8bSpwPaCieYy8',
    appId: '1:736451392421:web:baa2cfcfc868200ed02e4c',
    messagingSenderId: '736451392421',
    projectId: 'flutter-getx-eb2fd',
    authDomain: 'flutter-getx-eb2fd.firebaseapp.com',
    storageBucket: 'flutter-getx-eb2fd.appspot.com',
    measurementId: 'G-HC7K73X1SJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpwaTSi1pbDzgzKgsr0BRVUhs5mBIQUwU',
    appId: '1:736451392421:android:9446d9a68cb811fbd02e4c',
    messagingSenderId: '736451392421',
    projectId: 'flutter-getx-eb2fd',
    storageBucket: 'flutter-getx-eb2fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC757yIEnAaspJGaIXY74T4g5VZy_OV3Zc',
    appId: '1:736451392421:ios:1c293dd3caf1cfafd02e4c',
    messagingSenderId: '736451392421',
    projectId: 'flutter-getx-eb2fd',
    storageBucket: 'flutter-getx-eb2fd.appspot.com',
    iosBundleId: 'com.example.flutterGetxPractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC757yIEnAaspJGaIXY74T4g5VZy_OV3Zc',
    appId: '1:736451392421:ios:1c293dd3caf1cfafd02e4c',
    messagingSenderId: '736451392421',
    projectId: 'flutter-getx-eb2fd',
    storageBucket: 'flutter-getx-eb2fd.appspot.com',
    iosBundleId: 'com.example.flutterGetxPractice',
  );
}
